version: "3.7"

networks:
  kafka-cluster:
    name: kafka-cluster
    driver: bridge

volumes:
    zookeeper-data:
    zookeeper-datalib:
    zookeeper-datalog:
    zookeeper-datasecrets:
    zookeeper-dataloglib:
    kafka1-data:
    kafka2-data:
    # kafka3-data:
    debezium-data:
    sql-data:

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 22181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zookeeper-datalog:/datalog
      - zookeeper-data:/data
      - zookeeper-datasecrets:/etc/zookeeper/secrets
      - zookeeper-datalib:/var/lib/zookeeper/data
      - zookeeper-dataloglib:/var/lib/zookeeper/log
    networks:
      - kafka-cluster

  kafka1:
    image: confluentinc/cp-kafka:latest
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka1 -Dcom.sun.management.jmxremote.rmi.port=9991
    volumes:
      - kafka1-data:/var/lib/kafka/data
      - kafka1-data:/etc/kafka/secrets
    ports:
      - 9092:9092
    networks:
      - kafka-cluster

  kafka2:
    image: confluentinc/cp-kafka:latest
    depends_on: [zookeeper,kafka1]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9992
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka2 -Dcom.sun.management.jmxremote.rmi.port=9992
    volumes:
      - kafka2-data:/var/lib/kafka/data
      - kafka2-data:/etc/kafka/secrets
    ports:
      - 9093:9093
    networks:
      - kafka-cluster

  # kafka3:
  #   image: confluentinc/cp-kafka:latest
  #   depends_on: [zookeeper,kafka1,kafka2]
  #   environment:
  #     KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_BROKER_ID: 3
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_JMX_PORT: 9993
  #     KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka3 -Dcom.sun.management.jmxremote.rmi.port=9993
  #   volumes:
  #     - kafka3-data:/var/lib/kafka/data
  #     - kafka3-data:/etc/kafka/secrets
  #   ports:
  #     - 9094:9094
  #   networks:
  #     - kafka-cluster

# management UI Kafka

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka1:9092"
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      # - kafka3
    networks:
      - kafka-cluster

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9999:8080
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      # - kafka3
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka1
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9991
      KAFKA_CLUSTERS_1_NAME: kafka2
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: kafka2:9093
      KAFKA_CLUSTERS_1_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_1_JMXPORT: 9992
      # KAFKA_CLUSTERS_2_NAME: kafka3
      # KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS: kafka3:9094
      # KAFKA_CLUSTERS_2_ZOOKEEPER: zookeeper:2181
      # KAFKA_CLUSTERS_2_JMXPORT: 9993
    networks:
      - kafka-cluster

