version: '3.9'

services:
  client:
    image: nginx
    domainname: nginxconf
    ports:
      - '80:80'
    volumes:
      - nginxconfig:/etc/nginx/myconfig
      - nginxservice:/etc/systemd/system/multi-user.target.wants

volumes:
  nginxconfig:
    driver: azure_file
    driver_opts:
      share_name: nginxconfig
      storage_account_name: srpcontainerstorage
      storage_account_key: "XXXXXXXXXXX"

  nginxservice:
    driver: azure_file
    driver_opts:
      share_name: nginxservice
      storage_account_name: srpcontainerstorage
      storage_account_key: "XXXXXXXXXXX"
