version: "3.7"

networks:
  kafka-cluster:
    name: kafka-cluster
    driver: bridge

volumes:
    zookeeper-data:
    kafka1-data:
    kafka2-data:
    debezium-data:
    sql-data:

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 22181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zookeeper-data:/datalog
      - zookeeper-data:/data
      - zookeeper-data:/etc/zookeeper/secrets
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-data:/var/lib/zookeeper/log
    networks:
      - kafka-cluster

  kafka1:
    image: confluentinc/cp-kafka:latest
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
    volumes:
      - kafka1-data:/var/lib/kafka/data
      - kafka1-data:/etc/kafka/secrets
    ports:
      - 9092:9092
    networks:
      - kafka-cluster

  kafka2:
    image: confluentinc/cp-kafka:latest
    depends_on: [zookeeper,kafka1]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
    volumes:
      - kafka2-data:/var/lib/kafka/data
      - kafka2-data:/etc/kafka/secrets
    ports:
      - 9093:9093
    networks:
      - kafka-cluster

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka1:9092"
    depends_on: [kafka1,kafka2]
    networks:
      - kafka-cluster

